(in-package #:python.cffi)

;; Python must have been initialized for our macroexpansions to work.
(eval-when (:compile-toplevel :load-toplevel)
  (.initialize))

(defpyexception "BaseException" (python-condition)
    (("args" :initarg :args)))
(defpyexception "Exception" () ())
(defpyexception "StandardError" (python-error) ())
(defpyexception "ArithmeticError" () ())
(defpyexception "LookupError" () ())
(defpyexception "AssertionError" () ())
(defpyexception "AttributeError" () ())
(defpyexception "EOFError" () ())
(defpyexception "EnvironmentError" ()
    (("errno" :initarg :errno)
     ("strerror" :initarg :strerror)
     ("filename" :initarg :filename)))
(defpyexception "FloatingPointError" () ())
(defpyexception "IOError" () ())
(defpyexception "ImportError" () ())
(defpyexception "IndexError" () ())
(defpyexception "KeyError" () ())
(defpyexception "KeyboardInterrupt" () ())
(defpyexception "MemoryError" () ())
(defpyexception "NameError" () ())
(defpyexception "RuntimeError" () ())
(defpyexception "NotImplementedError" () ())
(defpyexception "OSError" () ())
(defpyexception "OverflowError" () ())
(defpyexception "ReferenceError" () ())
(defpyexception "SyntaxError" ()
    (("filename" :initarg :filename)
     ("lineno"   :initarg :lineno)
     ("offset"   :initarg :offset)
     ("text"     :initarg :text)))
(defpyexception "SystemError" () ())
(defpyexception "SystemExit" () ())
(defpyexception "TypeError" () ())
(defpyexception "ValueError" () ())
#+windows (defpyexception "WindowsError" () ())
(defpyexception "ZeroDivisionError" () ())

(eval-when (:compile-toplevel :load-toplevel)
  (.finalize))

#+(or) (burgled-batteries:run "1+")
